name: Refresh Trivandrum Recommender Data

# This makes the workflow run on a schedule
on:
  schedule:
    # Runs at 03:00 UTC on the 1st and 15th of every month
    - cron: '0 3 1,15 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run data pipeline
        run: |
          python data_pipeline/run_pipeline.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add -A
          # The following command will only commit if there are actual changes
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated data refresh"
          git push